--- 
 epochs: 500
 rnn_units: 412
 embedding_dim: 206
 batch_size: 108
 min_lr: 0.00006
 max_lr: 0.004
 min_delta: 0.0005 # for lr_scheduler
 vocab_file: vocab.npy
 data_file: trump-tweets-sm.csv
 checkpoint_dir: trump_training_checkpoints/current
 buffer_size: 100
 verbose: True
 encoding: ISO-8859-2
 base_dir: /home/jason/Documents