--- 
 epochs: 2
 rnn_units: 412
 embedding_dim: 206
 batch_size: 108
 min_lr: 0.00006
 max_lr: 0.004
 min_delta: 0.0005 # for lr_scheduler
 lr_factor: 0.2
 patience: 5
 vocab_file: vocab.npy
 data_file: trump-tweets-no-retweets-latest.json
 checkpoint_dir: trump_training_checkpoints/current
 buffer_size: 100
 verbose: True
 encoding: ISO-8859-2
 base_dir: /home/jason/internal/trump-change
 runs_dir: /home/jason/freya/runs